const NAME_SPACE = 'USER';

export default {
  FETCH_SIGN_IN_REQUEST: `${NAME_SPACE}/FETCH_SIGN_IN_REQUEST`,
  FETCH_SIGN_IN_FAILURE: `${NAME_SPACE}/FETCH_SIGN_IN_FAILURE`,
  FETCH_SIGN_IN_SUCCESS: `${NAME_SPACE}/FETCH_SIGN_IN_SUCCESS`,
  FETCH_SIGN_IN: `${NAME_SPACE}/FETCH_SIGN_IN`,
  FETCH_SIGN_UP_REQUEST: `${NAME_SPACE}/FETCH_SIGN_UP_REQUEST`,
  FETCH_SIGN_UP_FAILURE: `${NAME_SPACE}/FETCH_SIGN_UP_FAILURE`,
  FETCH_SIGN_UP_SUCCESS: `${NAME_SPACE}/FETCH_SIGN_UP_SUCCESS`,
  FETCH_SIGN_UP: `${NAME_SPACE}/FETCH_SIGN_UP`,
  SIGN_OUT_REQUEST: `${NAME_SPACE}/SIGN_OUT_REQUEST`,
  SIGN_OUT_FAILURE: `${NAME_SPACE}/SIGN_OUT_FAILURE`,
  SIGN_OUT_SUCCESS: `${NAME_SPACE}/SIGN_OUT_SUCCESS`,
  SIGN_OUT: `${NAME_SPACE}/SIGN_OUT`,
}
