const NAME_SPACE = 'PRODUCTS';

export default {
  FETCH_PRODUCTS_LIST_FAILURE: `${NAME_SPACE}/FETCH_PRODUCTS_LIST_FAILURE`,
  FETCH_PRODUCTS_LIST_REQUEST: `${NAME_SPACE}/FETCH_PRODUCTS_LIST_REQUEST`,
  FETCH_PRODUCTS_LIST_SUCCESS: `${NAME_SPACE}/FETCH_PRODUCTS_LIST_SUCCESS`,
  FETCH_PRODUCTS_LIST: `${NAME_SPACE}/FETCH_PRODUCTS_LIST`,
}
